{% set name = "pyotp" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 346b6642e0dbdde3b4ff5a930b664ca82abfa116356ed48cc42c7d6590d36f63

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyotp

about:
  home: https://github.com/pyauth/pyotp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python One Time Password Library
  description: 'PyOTP - The Python One-Time Password Library. PyOTP is a Python library for generating and verifying one-time passwords. It can be used to implement two-factor (2FA) or multi-factor (MFA) authentication methods in web applications and in other systems that require users to log in. '
  doc_url: https://pyotp.readthedocs.io/
  dev_url: https://github.com/pyauth/pyotp

extra:
  recipe-maintainers:
    - kalling
    - smithsp
    - jan-janssen
