{% set name = "pyotp" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2f5e17d9da92d8ec1f7de6331ab08116b9115adbabcba6e208d46fc49a98c5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyotp

about:
  home: https://github.com/pyauth/pyotp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python One Time Password Library
  description: 'PyOTP - The Python One-Time Password Library. PyOTP is a Python library for generating and verifying one-time passwords. It can be used to implement two-factor (2FA) or multi-factor (MFA) authentication methods in web applications and in other systems that require users to log in. '
  doc_url: https://pyotp.readthedocs.io/
  dev_url: https://github.com/pyauth/pyotp

extra:
  recipe-maintainers:
    - kalling
    - smithsp
