{% set name = "pyotp" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce989faba0df77dc032b45e51c6cca42bcf20896c8d3d1e7cd759a53dc7d6cb5

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pyotp

about:
  home: https://github.com/pyauth/pyotp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python One Time Password Library
  description: 'PyOTP - The Python One-Time Password Library. PyOTP is a Python library for generating and verifying one-time passwords. It can be used to implement two-factor (2FA) or multi-factor (MFA) authentication methods in web applications and in other systems that require users to log in. '
  doc_url: https://pyotp.readthedocs.io/
  dev_url: https://github.com/pyauth/pyotp

extra:
  recipe-maintainers:
    - kalling
    - smithsp
    - jan-janssen
